name: Android Release CI with Flavor & Signing

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        flavor: [staging]

    steps:
      - name: ğŸ”„ Checkout Repository
        uses: actions/checkout@v4

      - name: ğŸ› ï¸ Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml

      - name: ğŸ“¦ Install dependencies
        run: flutter pub get

      - name: ğŸ” Flutter version
        run: flutter --version

      - name: ğŸ—ï¸ Decode keystore.jks from secret
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE }}" | base64 -d > android/app/keystore.jks

      - name: ğŸ—‚ï¸ Create key.properties file
        run: |
          cat <<EOF > android/key.properties
          storePassword=${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword=${{ secrets.ANDROID_ALIAS_PASSWORD }}
          keyAlias=${{ secrets.ANDROID_ALIAS }}
          storeFile=keystore.jks
          EOF

      - name: "ğŸ— Build Signed APK with Flavor: ${{ matrix.flavor }}"
        run: |
          flutter build apk --obfuscate --split-debug-info=out/android --flavor ${{ matrix.flavor }} -t lib/main_${{ matrix.flavor }}.dart

      - name: ğŸ“¦ Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.flavor }}-release-apk
          path: build/app/outputs/apk/${{ matrix.flavor }}/release/app-${{ matrix.flavor }}-release.apk
